#+Title: Requirement 2: Basic Scalable OpenEdX Deployment
#+Date: Friday, August 5, 2016
#+Author: Mr. Maruthi Rao


* Objective
  Getting control of OpenEdX deployment and to a reasonable level of
  scale. Say at least 500 concurrent students working.

* Current Status
  + LMS, CMS and DB are installed in one instance. This will cause
    severe challenges in scaling, performance.  And it is getting
    manifested in rigidity of the system.

  + User <-> {LMS, CMS, DB ++ All in one box}

* What Next ? 
  + A basic distributed structure will look like as below ::
   #+BEGIN_SRC 


      User <-> Load Balancer <-> LMS #1 --
                                 LMS #2 --     DB Server Farm
                                   :
                                 LMS #N -- 
                                   :
                                 CMS #1 --                              
   #+END_SRC


  + We will have  ::
    + 2 C3/C4 machines for LMS
    + 1 C3/C4 machine for CMS
    + 1 M3/M4 machine for DB Server
    + 1 Elastic Load Balancer or HA Proxy (as needed)
    + Note: There is no clustering. If it works as expected, we can extend it.
           
    + LMS serves OpenEdX pages to Students (Learners)
    + CMS serves managing the courses.
    + CMS need not be a cluster / farm. A single machine suffice.
    + LMS need to be under Load Balancing.

  + Time frame :: 
    1 Week of Experimentation needed to stabilise platform at least.

* Who is working?
  I asked Siva (and time sharing with Ahay) to work on the above
  deployment model and we will make a simple arch. document for
  further reference.

* Testing
  It is really a tough task. We need to take some external help to
  develop Selenium, PhantomJS test suits. Maybe for some critical
  paths.

* How it helps in Lab Porting?
  The proposed set up is Platform Architecture. It should not affect
  current activities the porting of LABs.
