#+TITLE: Manage the Open edX platform (LMS and CMS)
#+Author: VLEAD
#+Date: [2016-02-23 Tue]

* Introduction
  This document describes the managing Open edX paltform
* Upgrade Open edX platform from older/past release to the newer release 
*** Upgrade from birtch.2 release to cypress release  
    - Export 
      #+BEGIN_EXAMPLE
      export OPENEDX_RELEASE="named-release/cypress"
      #+END_EXAMPLE    
    - Run 
      #+BEGIN_EXAMPLE
      cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"     
      #+END_EXAMPLE
    - Successfully upgraded/migrated to cypress
*** Setup Open edX platform with named-release/birtch.2
    - Launch an Ubuntu 12.04 64 bit (ami-019b6745)  instance on AWS
      + RAM : 4 GB 
      + HDD : 50 GB
    - Update and upgrade the machine
    - Install 
      #+BEGIN_EXAMPLE
      sudo apt-get install -y build-essential software-properties-common python-software-properties curl git-core libxml2-dev libxslt1-dev libfreetype6-dev python-pip python-apt python-dev libxmlsec1-dev swig libmysqlclient-dev
      sudo pip install --upgrade pip
      sudo pip install --upgrade virtualenv
      #+END_EXAMPLE
    - Perform the steps
      #+BEGIN_EXAMPLE
      cd /var/tmp
      git clone https://github.com/edx/configuration
      #+END_EXAMPLE
    - Allow password based SSH authentication, for that do the
      following 
      #+BEGIN_EXAMPLE
      cd configuration/
      vim configuration/playbooks/roles/common_vars/defaults/main.yml
      #+END_EXAMPLE
      and set =COMMON_SSH_PASSWORD_AUTH= to "yes"
    - Issue the following command to install required packages.
      #+BEGIN_EXAMPLE
      sudo pip install -r requirements.txt
      #+END_EXAMPLE
    - Export 
      #+BEGIN_EXAMPLE
      export OPENEDX_RELEASE="named-release/birch.2"
      #+END_EXAMPLE
    - Install paramiko package
      #+BEGIN_EXAMPLE
      sudo pip install paramiko==1.10
      #+END_EXAMPLE
    - Run 
      #+BEGIN_EXAMPLE
      cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"     
      #+END_EXAMPLE
    - Open edX platform has been setup with the
      "named-release/birtch.2"
*** Downgrading the Open edX platform (Don't do this, It does not work)
**** Example
     Suppose,you have the latest version(Dogwood) of the Open edX
     platform setup, If you want to upgrade to the older version, you
     can follow the below steps. But it will not work (We may get
     Database sync/migration problem).
* Work around the configuration files of Open edX setup.
** Create superuser for Django administration page
   Create super user by issuing following commands on the LMS machine.

   - Create superuser (with profile) ::  Replace "user@example.com"
        with the email address you want to use, and replace "user"
        with the first part of the email address that you used. So for
        example, if you use "staff+87@yourdomain.com" for the email
        address, the username will be "staff+87".
     #+BEGIN_EXAMPLE 
     cd /edx/app/edxapp/edx-platfrom/
     sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws create_user -s -p edx -e user@example.com
     sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws changepassword user
     sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws shell
     from django.contrib.auth.models import User
     me = User.objects.get(username="user")
     me.is_superuser = True
     me.is_staff = True
     me.save()
     #+END_EXAMPLE
   - Create superuser (without profile) ::
     #+BEGIN_EXAMPLE 
     sudo su edxapp -s /bin/bash
     cd ~
     source edxapp_env
     python /edx/app/edxapp/edx-platform/manage.py lms createsuperuser --settings aws
     #+END_EXAMPLE
   - Reference
     https://openedx.atlassian.net/wiki/display/OpenOPS/Managing+OpenEdX+Tips+and+Tricks
** Remove default users from Open edX platform
   For this we need superuser. superuser can be created using the
   steps mentioned in [[Create superuser for Django administration page]]
   
   Then 
   - Log in to django administration page
     #+BEGIN_EXAMPLE
     http://<lms-domain-name>/admin
     #+END_EXAMPLE
   - Navigate to =Authentication and Autherization= table and choose
     =Users=.
   - =Users= table lists all the default users and one django admin
     user.
   - Delete all default users except django admin user if you really want to delete.
     - Select default users which you want to delete by selecting
       check boxes provided in front of every user
     - Choose Action drop down menu and select "Delete selected users"

** Add/Create required users to log in to LMS/CMS
   For this also we need superuser. superuser can be created using the
   steps mentioned in [[Create superuser for Django administration page]]
   
   Then 
   - Log in to django administration page
     #+BEGIN_EXAMPLE
     http://<lms-domain-name>/admin
     #+END_EXAMPLE
   - Navigate to =Authentication and Autherization= table and choose
     =Users=.
   - Click on =Add user= button in top right corner
   - Create a new user by providing user name and password
   - Then click on =Save and Continue= button and provide proper
     permissions to that user.
      
** Deleting a course from Open edX Studio
   - Delete a particular course using the following command 
     #+BEGIN_SRC
     cd /edx/app/edxapp/edx-platform/
     sudo -u www-data /edx/bin/python.edxapp ./manage.py cms --settings=aws delete_course course-v1:Organization+CourseNumber+CourseRun commit
     #+END_SRC
   - For example, if we want to delete course
     course-v1:IIITH+pevii+2016_T11(course-v1:Organization+CourseNumber+CourseRun)
     then issue following command in command line
     #+BEGIN_EXAMPLE
     sudo -u www-data /edx/bin/python.edxapp ./manage.py cms --settings=aws delete_course course-v1:IIITH+pevii+2016_T11
     #+END_EXAMPLE
     The above command will ask you whether to delete course or not ,
     proceed accordingly.
* References
  - https://github.com/edx/configuration/wiki/edX-Managing-the-Full-Stack
  - http://oonlab.com/edx/code/2015/10/21/solve-celery-error-saat-migrasi-open-edx/
  - https://groups.google.com/forum/#!topic/openedx-ops/1SsdJ39IQRc
