#+TITLE: Manage the Open edX platform (LMS and CMS)
#+Author: VLEAD
#+Date: [2016-04-29 Fri]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-0.org


* Introduction
  This document describes the managing Open edX paltform
* Administration tasks on Open edX platform
** Create superuser for Django administration page
   To perform any administration tasks from Django administration web console,
   this step is mandatory. 

   Creation of super user with profile is recommended. 
   
   - <<super user>> Create superuser (with profile) ::  Replace "user@example.com" with the
        email address you want to use, and replace "user" with the first part
        of the email address that you used. So for example, if you use
        "staff+87@yourdomain.com" for the email address, the username will be
        "staff+87".
     #+BEGIN_EXAMPLE 
     cd /edx/app/edxapp/edx-platfrom/
     sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws create_user -s -p edx -e user@example.com
     sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws changepassword user
     sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws shell
     from django.contrib.auth.models import User
     me = User.objects.get(username="user")
     me.is_superuser = True
     me.is_staff = True
     me.save()
     #+END_EXAMPLE
   - Create superuser (without profile) ::
     #+BEGIN_EXAMPLE 
     sudo su edxapp -s /bin/bash
     cd ~
     source edxapp_env
     python /edx/app/edxapp/edx-platform/manage.py lms createsuperuser --settings aws
     #+END_EXAMPLE
   - Reference
     https://openedx.atlassian.net/wiki/display/OpenOPS/Managing+OpenEdX+Tips+and+Tricks
** Remove default users from Open edX platform
   For this we need superuser. superuser can be created using the steps
   mentioned in [[super user]] for Django administration page.
  
   After creation of super user, follow the following steps. 
   
   - Log in to django administration page
     #+BEGIN_EXAMPLE
     http://<lms-domain-name>/admin
     #+END_EXAMPLE
   - Navigate to =Authentication and Authorization= table and choose
     =Users=.
   - =Users= table lists all the default users and one django admin
     user.
   - Delete all default users except django admin user if you really want to delete.
     - Select default users which you want to delete by selecting
       check boxes provided in front of every user
     - Choose Action drop down menu and select "Delete selected users"

** Add/Create required users to log in to LMS/CMS
   A [[super user]] is needed for accomplishing this task.  If super user is not
   present, please create a [[super user]].
   
   Once this is done, follow the steps below. 

   - Log in to django administration page
     #+BEGIN_EXAMPLE
     http://<lms-domain-name>/admin
     #+END_EXAMPLE
   - Navigate to =Authentication and Authorization= table and choose
     =Users=.
   - Click on =Add user= button in top right corner
   - Create a new user by providing user name and password
   - Then click on =Save and Continue= button and provide proper
     permissions to that user.
      
** Deleting a course from Open edX Studio
   - Delete a particular course using the following command 
     #+BEGIN_SRC
     cd /edx/app/edxapp/edx-platform/
     sudo -u www-data /edx/bin/python.edxapp ./manage.py cms --settings=aws delete_course course-v1:Organization+CourseNumber+CourseRun commit
     #+END_SRC
   - For example, if we want to delete course
     course-v1:IIITH+pevii+2016_T11(course-v1:Organization+CourseNumber+CourseRun)
     then issue following command in command line
     #+BEGIN_EXAMPLE
     sudo -u www-data /edx/bin/python.edxapp ./manage.py cms --settings=aws delete_course course-v1:IIITH+pevii+2016_T11
     #+END_EXAMPLE
     The above command will ask you whether to delete course or not ,
     proceed accordingly.

** Start/Stop/restart/ all services of edX
#+BEGIN_SRC 
1. /edx/bin/supervisorctl start all
2. /edx/bin/supervisorctl stop all
3. /edx/bin/supervisorctl restart all
4. /edx/bin/supervisorctl status all
#+END_SRC


* References
  - [[https://openedx.atlassian.net/wiki/display/OpenOPS/Managing+OpenEdX+Tips+and+Tricks][Manage Open edX, Tips & Tricks]]
  

