#+Title: Authoring of Virtual Labs in Open edX Platform
#+Author: VLEAD
#+Email: engg@vlabs.ac.in
#+DATE: [2016-09-29 Thurs]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+LANGUAGE: en
#+OPTIONS: ^:nil

* Introduction
  Virtual Labs is a mission mode project initiated by the Ministry of
  Human Resources and Development (MHRD), India. The objective of this
  project is to provide laboratory learning experience to the students
  who do not have access to adequate laboratory infrastructure.
  Currently there are around more than 100 labs which have been
  developed by various institutes.The authoring of Virtual Labs in
  Open edX platform described in this document defines the creation
  and hosting of a new lab in the Open edX platform. It aims at
  delivering responsive, open-source and device-independent labs,
  helping us in our strive for excellence.
* Motivation
  This document is driven by the commitment of delivering a new
  lab on Open edX platform which can be accomplished by
  following an efficient authoring process. The entire workflow
  starting from the creation of a new lab to publishing it for
  the end user is detailed in the followings sections.
* Authoring of a lab on Open edX 
** Lab structure of a typical Virtual-Lab
 + A typical Virtual-Lab is structured with the following sections :
   + Introduction
   + List of Experiments
   + Target Audience
   + Courses
   + Pre-requisites
   + Feedback
 + Inside the above mentioned *List of Experiments*, several
   experiments could be listed with following sections (sections could
   vary from one experiment to other) :
   + Introduction
   + Theory
   + Objective
   + Experiment
   + Manual
   + Quizzes
   + Procedure
   + References
   + Feedback
** Request of a new lab
   + A new lab request should be raised as an issue in [[https://github.com/Virtual-Labs/engineers-forum/issues][engineers-forum]]
     in Virtual-Labs organisation in GitHub.
** Creation of lab specifications
   The Central Team would create the lab specifications in the [[http://www.json.org/][json]]
   format and push in the [[https://github.com/openedx-vlead/lab-specifications][GitHub repo]]. They would follow the below
   steps to create the required structure of the lab for Open edX :
   + The example [[https://github.com/openedx-vlead/port-labs-to-openedx/blob/develop/src/porting-labs/labspec.json][labspec.json]] file could be used for creating the Open
     edX structure of the requested lab.
   + This [[https://github.com/openedx-vlead/port-labs-to-openedx/blob/develop/src/porting-labs/labspec.json][example file]] could be edited to replicate the desired lab
     structure.
   + The "course" field must be filled with the values of "org", "id",
     "display_name" and "overview" as Organization Name, Lab Id, Name
     of the lab and Description of the lab respectively. Lab Ids could
     be obtained from [[https://docs.google.com/spreadsheets/d/1qIU42qaMVtwpP_6eV3YXjJs8CJb6wnPPclFgqbGdlCM/edit?usp=sharing][here]]. Lab Ids should be given in capital letters
     for uniformity and white spaces or special characters must be
     avoided in the same.
   + The "experiments" field must be entered with the list of all the
     experiments for the particular lab.
   + If the lab also includes fields like Target Audience, Courses
     Aligned, Feedback etc, they have to be created as separate
     sections in labspec.json file.
   + For the "experiments" field, the first two fields called =name=
     and =subsections= must be left unchanged as =Introduction=.
   + The rest of the =name= and =subsections= fields below should be
     filled with the names of the subsections of the the various
     experiments of the lab.
   + Care needs to be taken while creating the labspec.json file. For
     verifying the correctness of the json file and avoid any errors,
     checking the file with [[http://jsonparseronline.com][json parser]] is strongly recommended.
   + The created labspec.json file would be provided to the lab author
     for creating the course.
** Creation of lab by the author
   + The lab specification file created by the Central Team would be
     provided to the lab author and he/she would create the lab
     referring to the given values :
     + Course Name
     + Organisation Name
     + Course ID
     + Course Start Date
   + The lab author would be given the staging instance of Open edX
     platform to create the lab.
   + [[http://open-edx.vlabs.ac.in:18010/][Open edX Studio]] have to be signed in to create the lab which is
     analogous to a course in edX terminologies. First time users
     would have to register to create a lab. In order to view the
     created lab, [[http://open-edx.vlabs.ac.in][Open edX LMS]] (Learning Management System) should be
     visited.
   + Click on =New Course= button on top right corner to start
     creating the new lab.
   + Fill the Course Name, Organisation, Course Number and Course Run
     as per the labspec.json and click on =Create Course=.
   + The content of the lab (HTML/text/images/simulations) would be
     placed in the units. For a better insight, referring the link :
     [[https://www.edx.org/course/creating-course-edx-studio-edx-studiox][Creating a course with Open edX Studio]] is strongly
     recommended. Following the above link is highly recommended as it
     would enhance the understanding of Open edX terminologies and
     their usage.
    + Difference between published and released content, different
      views with staff and student views in LMS could be learnt in
      greater details from : [[https://www.edx.org/course/creating-course-edx-studio-edx-studiox][Creating a course with Open edX Studio]]\\
 The following sections describe the methods to include the different
 components of a lab in Open edX platform -
*** Including the text content
    + Click on =+ New Section= to create a new section for an
      experiment in the lab and hit Enter to save it.
    + Click on =+ New Subsection= to create new subsections named
      *Aim* , *Theory* , *Simulation* , *Video* etc based on the
      labspec details and hit Enter to save it.
    + For Example : For *Aim* subsection, click on =+ New Unit= to
      create a unit named *Aim*.
      + Click on =HTML= from Add New Component and select =Text=
        field.
      + Click on =EDIT= tab at top right corner of editor, write/paste
        the required content and click on =Save=.
      + Go back to *Aim* subsection on Studio Home to create more
        units if required.
      + Create another subsection named *Theory*, follow the same
        process as that of *Aim* and write the required content.
*** Including the simulations
    + Click on =+ New Unit= to create a unit named *Simulation*. If
      the simulation is termed as experiment or coined as some other
      term, that needs to be used here. It is not a mandate to use
      simulation term only.
    + Click on =HTML= from Add New Component and select =IFrame Tool=
      field.
    + Click on =EDIT= tab and select =HTML=, the last icon on the
      editor.
    + Include the iframe code for the simulations which might be
      served from other servers (not from Open EdX platform). In case
      the simulations are not hosted anywhere, the entire code could
      be included for rendering the simulations. Click on =Save= to
      save the changes.
    + If there are multiple simulators for a single experiment, those
      would be created in different units within the same subsection.
    + The below code should be included in the HTML source code
      editor. The =src= field would include the https simulation URL
      if it is already hosted on a server. There would be a full
      screen button also included to open the simulator in a new full
      screen/window on the browser.
    + To ensure link integrity, the =https= URL must be included in
      the iframes of simulations. In case for any lab SSL certificates
      are not available, =http= URL should be included.
#+BEGIN_EXAMPLE
    <p><button onclick="popup()">Full Screen</button></p>
<p></p>
<p><iframe src="https://...." height="602" width="802"> </iframe></p>
<script>// <![CDATA[
function popup(){
  window.open('https://....', '_blank', 'toolbar=0,location=0,menubar=0');
 }
// ]]></script>
#+END_EXAMPLE
*** Including the analytics
     + Analytics code should be included in each simulation code in
       order to capture the usage for each experiment performed by a
       student. The analytics code is given below :

   #+BEGIN_SRC command
   <p><button onclick="popup()">Full Screen</button></p>
   <p><iframe src="http://pevii-au.virtual-labs.ac.in/index.php?exp_id=Optimal_Foraging_Pollinators" height="602" width="802"> </iframe></p>
   <script>// <![CDATA[
   function popup(){
    window.open('http://pevii-au.virtual-labs.ac.in/index.php?exp_id=Optimal_Foraging_Pollinators', '_blank', 'toolbar=0,location=0,menubar=0');
    }
   //  ]]></script>

   <script type="text/javascript">
    // ****** ALSO MODIFY THE URLS GIVEN ABOVE **************
   // ********MODIFY THIS SECTION **************************

   var courseid = "pevii-au";
   var experiment_name = "Optimal Pollinators"
   var lab_name = "Population Ecology II"
    
   // *******DO NOT MODIFY THIS SECTION AGAIN **************
   </script>
   <script src="https://github.com/openedx-vlead/lab-usage-tracker/blob/master/src/common.js"></script>
   #+END_SRC
  *NOTE* : 
  + In the above code snippet, the =src= field would include the https
    simulation URL if it is already hosted on a server. There would be
    a full screen button also included to open the simulator in a new
    full screen/window on the browser. The =https= URL given above in
    the example code snippet is only for representational
    purposes. *Kindly refrain from giving the same https URLs as given
    in above example*.
  + The =var= fields should be filled with appropriate courseid,
    experiment_name and lab_name with labid, experiment_name and
    lab_name of the authored lab respectively.
  + To ensure link integrity, the =https= URL must be included in the
    iframes of simulations. In case of unavailability of lab SSL
    certificates, =http= URL should be included.
*** Including the feedback
*** Including the videos
    + Click on =+ New Unit= to create a unit named *Video*
    + Choose the =Video= component from Add New Component.
    + Click on =EDIT= tab and include the URL of the video to be added
      in =Default Video URL= field.
    + If the video includes timed scripts, then it should also be
      included in the =Default Timed Transcript= field
    + Click on =Save= to save the changes.
*** Including the images
    Direct copy pasting the images works sometimes and sometimes
    doesn't. Other method to inlcude the images is given below : 
    + Images can be uploaded from =Content= tab, selecting the =Files
      and Uploads= option.
    + Upload the image using =+ Upload New File= and provide the
      =Studio URL= given to render the image.
*** Including the quiz
    + Select the =Problem= component from Add New Component after
      creating a new unit named =Quiz=.
    + Depending on the type of quiz, select the option for creating
      different quizzes.
*** Authoring the lab with database
    Currently we would not support any lab authoring request with a
    database.
*** Publishing the lab content
    Click on the upward arrow icon in each section for publishing all
    the contents of a section. Without publishing the content, it
    would not be visible on the Open edX Learning Management System
    (LMS).
*** Miscellaneous modifications
   Few more steps to make other modifications by the author are listed
   below :
**** Modification of lab date to =Anytime=
     + Click on Course name which you own.
     + Go to settings drop down, and click Advanced settings.
     + Change field “Course Advertised Start Date” from null to
       “Anytime”
     + Save your changes
**** Modification of the default lab preview and lab image
     + Click on Course name.
     + Go to =schedule and details= in settings drop down.
     + Leave all the fields in course schedule empty except for the
       first field which should be any date previous to current date.
     + In “Introducing your Course” section edit the “Course Overview”
       as per the requirement.
     + Add a course image by clicking on Upload image button.
     + Save the changes.
** Exporting the lab
     + Click on =Tools= dropdown menu option from top. Click on
       =export= option.
     + Choose the =Export Course Content= option and save the tar.gz
       file of the created lab in the local machine which could be
       pushed as sources to GitHub.
     + The author/creator would attach the tar.gz file of the course
       with all the contents in the same issue where the course
       creation was request (Engineers-Forum).
*** Lab content after exporting
     When a course is exported, edX CMS/studio creates a tar.gz file
     that includes the following course data.
     + Course content (all Sections, Subsections, and Units)
     + Course structure
     + Individual problems
     + Pages
     + Course assets
     + Course settings
     The following data is not exported with the course.
     + User data
     + Course team data
     + Discussion data
     + Certificates   
** Hosting of lab
   Central Team would import it on the production edX machine after
   verification of all the course credentials as per the lab
   specifications. The lab would now be available for all the users.
*** Creation of a repository on GitHub 
    + Export the lab from =Tools= dropdown menu on the top of the
      Studio. A zipped file is downloaded. Unzip and untar the
      exported file to produce a directory.
      + Command =tar zxvf testlab.tar.gz= forms a tar.gz file.      
    + Create a repository in the github in =openedx-vlead=
      organisation with the same name as that of the lab preceeded by
      term =open-edx=
    + Clone the newly created repository.
    + Copy the entire contents of the directory created in step 1 to the
      directory created in step 3.
    + Add, commit and push all the changes to the git repository.
* Disclaimer
  VLEAD team at IIIT-H would be only responsible for the creation of
  lab speicifications called labspec.json files. They would provide
  the labspecs and the information provided must be adhered by the lab
  author while creating a course on Open edX. Subsequent to the
  availability of labspecs, each author would be responsible for the
  content of a course. Also subsequent to the course creation on the
  staging instance by the author, the hosting request for the course
  on production edX environment should be raised in the
  engineers-forum after the initial credentials of a course are as per
  the lab specifications.
* Summary
  This document highlights the authoring of a new course from course
  creation to hosting. It focusses on the process to contribute
  towards Open edX courses and deliver high quality labs. It also aims
  at collaborating contributions of the developers across the open
  source platform - Open edX. This streamlined process would help in
  our strive for excellence in delivering high standard labs.
* Glossary
  - *Git* : Git is a free and open source distributed version control
    system designed to handle everything from small to very large
    projects with speed and efficiency.
  - *GitHub* : /[[https://github.com/][GitHub]]/ is a web-based Git repository hosting service,
    which offers all of the distributed revision control and source
    code management (SCM) functionality of Git as well as adding its
    own features.
  - *Central Team* : The central team refers to VLEAD team at
    IIIT-Hyderabad and they would be responsible for creating the lab
    specifications and hosting the labs on production.
  - *Repository* : The distributed version control system - git is
    used here. Every time the term repository or repo is used, it
    refers to a git repository. A repository is an on-disk data
    structure which stores metadata for a set of files and/or
    directory structure. The whole set of information in the
    repository may be duplicated on every user's system or may be
    maintained on a single server.
  - *Virtual Labs* : [[http://vlabs.ac.in/index.html#aboutus][Virtual Labs]] is an initiative by MHRD under
    NMEICT. The objective is to make engineering education engaging,
    enjoyable, immersive and online.
  - *VLEAD* : Virtual Labs Engineering and Architecture Division is
    the central engineering team of Virtual Labs that takes cares of
    both the research and development needs of the laboratory.
  - *Open edX Platform* : [[https://open.edx.org/about-open-edx][Open edX]] is the open source platform that
    powers edX courses. EdX offers interactive online courses and
    MOOCs from the world’s best universities and institutions. The
    Open edX Platform of Virtual-Labs hosts all the Virtual-Labs labs
    on the Open edX platform just like edX courses are powered.
  - *Learning Management System (LMS)* : The LMS is the Open edX tool
    that learners use to access course content, including videos,
    textbooks, and problems, and to check their progress in the
    course. The Open edX LMS also offers a discussion forum and a wiki
    that both learners and course team members can contribute to. We
    use the LMS directly through a [[http://open-edx.vlabs.ac.in/][browser]]. No additional software is
    required for this.
  - *Staging Instance* : Staging instance refers to the server machine
    (by Central Team) used for the hosting of the lab in an
    environment similar to production so that control to the
    production machine can be controlled. Both the staging instance as
    well as production instance would be controlled by Central Team.
  - *Author* : The author refers to the person who requests for the
    creation of a new lab on Open edX platform and holds all the
    authority over the lab content. The author would be the
    responsible person for the content of the lab on the Open edX.
  - *Production* : The production machine/server refers to the
    production environment where the requested new labs would be
    hosted/deployed for the end users.
